apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: edge
    app: edge-sensor14
  name: edge-sensor14
spec:
  replicas: 1
  selector:
    matchLabels:
      layer: edge
      app: edge-sensor14
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        layer: edge
        app: edge-sensor14
    spec:
      containers:
        - name: edge-sensor14
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'HojTx56asus1nniIw8OE'
          - name: host
            value: 'mytbedge.regiona.svc.kcluster.myanmarapn.com'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
