apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 15m
  path: "./kustomize/postgres"
  prune: true
  sourceRef:
    kind: GitRepository
    name: mytbedge

