apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 15m
  path: "./deploy/postgres"
  prune: true
  sourceRef:
    kind: GitRepository
    name: mytbedge

