apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor19
  name: edge-sensor19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor19
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor19
    spec:
      containers:
        - name: sensor19
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'qgzVRgN1vQYjRSTD1PKT'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
