apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor20
  name: edge-sensor20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor20
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor20
    spec:
      containers:
        - name: sensor20
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'MdmMS9sYZcOmI5chxMOW'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
