apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor01
  name: edge-sensor01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor01
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor01
    spec:
      containers:
        - name: sensor01
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'nr4ZIG363Yuu1xteEILc'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
