apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor07
  name: edge-sensor07
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor07
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor07
    spec:
      containers:
        - name: sensor07
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'iAnuYCNl47W3hHrBLXD7'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
