apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor17
  name: edge-sensor17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor17
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor17
    spec:
      containers:
        - name: sensor17
          image: 270596/evn_img:latest
          env:
          - name: token
            value: '0WV4IvpBi9YpCm8uGPLC'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
