apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor11
  name: edge-sensor11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor11
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor11
    spec:
      containers:
        - name: sensor11
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'PZ54T62x1N3Tqhy3RMQt'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
