apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor18
  name: edge-sensor18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor18
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor18
    spec:
      containers:
        - name: sensor18
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'CPMLKEO1yEAoaCW7SgJZ'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
