apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor06
  name: edge-sensor06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor06
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor06
    spec:
      containers:
        - name: sensor06
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'tpz7nZBSuTUwzK3zZnyI'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
