apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor02
  name: edge-sensor02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor02
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor02
    spec:
      containers:
        - name: sensor02
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'yos7WiMFLHwvvBpUQDqV'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
