apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor04
  name: edge-sensor04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor04
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor04
    spec:
      containers:
        - name: sensor04
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'MRNMqytcUUBQJOo1Yb5z'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
