apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor13
  name: edge-sensor13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor13
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor13
    spec:
      containers:
        - name: sensor13
          image: 270596/evn_img:latest
          env:
          - name: token
            value: '85w29Zfw7airWpb7pThR'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
