apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    layer: edge
    io.kompose.service: mytbedge
  name: mytbedge
  namespace: regiona
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mytbedge
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        layer: edge
        io.kompose.service: mytbedge
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: geol
                operator: In
                values:
                - regiona
      containers:
        - env:
            - name: CLOUD_ROUTING_KEY
              value: bd0b2a60-eedf-6900-e5ba-d3cb2e09b9dd
            - name: CLOUD_ROUTING_SECRET
              value: 14kkmnmy7jscec8m0u2m
            - name: CLOUD_RPC_HOST
              value: demo.thingsboard.io
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.regiona.svc.kcluster.myanmarapn.com:5432/tb-edge
          image: thingsboard/tb-edge:3.4.3EDGE
          name: mytbedge
          ports:
            - containerPort: 8080
            - containerPort: 1883
            - containerPort: 5683
              protocol: UDP
            - containerPort: 5684
              protocol: UDP
            - containerPort: 5685
              protocol: UDP
            - containerPort: 5686
              protocol: UDP
            - containerPort: 5687
              protocol: UDP
            - containerPort: 5688
              protocol: UDP
          resources: 
            limits: 
              cpu: "2000m"
              memory: "4.5Gi"
            requests:
              cpu: "1500m"
              memory: "4Gi"
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 180
            periodSeconds: 120
            failureThreshold: 3
      restartPolicy: Always
