apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mytbedge
  namespace: flux-system
spec:
  interval: 60s
  path: "./kustomize/edge"
  prune: true
  sourceRef:
    kind: GitRepository
    name: mytbedge
