apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sensor05
  name: edge-sensor05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor05
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensor05
    spec:
      containers:
        - name: sensor05
          image: 270596/evn_img:latest
          env:
          - name: token
            value: 'nPW6RKicoOkVVcA42Yxp'
          - name: host
            value: 'demo.thingsboard.io'
          - name: port
            value: '1883'

      restartPolicy: Always
status: {}
